# Uncomment the next line to define a global platform for your project
 platform :ios, '13.0'

target 'covid19_india' do
  # Comment the next line if you don't want to use dynamic frameworks
 pod 'GoogleMaps'

  use_frameworks!


  # Pods for covid19_india

end
